### ISSUE TITLE
Update for newer firmware?

### ISSUE THREAD

**Issue by cbasolutions** [Kibbles/polyboot#4]
Do you have any plans to update for the newer firmware? I think this current method was cut off in favor of the rest api which is disabled by default. 

I was able to chain it together in Postman. post for auth, get index for CSRF token in the head, and then reboot. 

csrf token header for post to reboot is anti-csrf-token

I used a browser developer tool to sort it all out.

**Comment by Kibbles** [comment]
I unfortunately don't have access to any Polycom hardware anymore, but they do have a Powershell example for a reboot in their FAQ that can be adapted:
https://community.poly.com/t5/VoIP-SIP-Phones/FAQ-REST-API/td-p/98914

**Comment by cbasolutions** [comment]
Thanks, that won’t work. By default API is disabled and the service provider isn’t able to make a global change. I’ll just slog through it ;).
